<?php
/**
 * @file
 * Code for the CA Gallery feature.
 */

include_once 'ca_gallery.features.inc';

/**
 * Implements hook_menu()
 */
function ca_gallery_menu() {
  $items['admin/config/worx_features/gallery'] = array(
    'title' => 'Gallery Configuration',
    'description' => 'Override settings for ca_gallery',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_gallery_settings_form'),
    'access arguments' => array('worx features admin'),
    'file' => 'ca_gallery.admin.inc',
    'file path' => drupal_get_path('module', 'ca_gallery'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/worx_features/gallery/general'] = array(
    'title' => 'General Settings',
    'description' => 'Override settings for ca_gallery',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_gallery_settings_form'),
    'access arguments' => array('worx features admin'),
    'file' => 'ca_gallery.admin.inc',
    'file path' => drupal_get_path('module', 'ca_gallery'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  return $items;
}

/**
 * implements hook_menu_alter().
 */
function ca_gallery_menu_alter(&$items) {
  $items['event']['title'] = variable_get('ca_gallery_menu_title', 'Gallery');
}

/**
 * Implements hook_panels_pre_render().
 */
function ca_gallery_panels_pre_render($panel, $renderer) {
  if (isset($panel->content['new-6']) && $panel->content['new-6']->subtype == 'ca_event-ca_event_list_1') {
    $panel->title = variable_get('ca_gallery_panel_title', 'Gallery');
  }
}

/**
 * Implements hook_views_pre_render().
 */
function ca_gallery_views_pre_view(&$view, &$display_id, &$args) {
  if ($display_id == 'ca_event_list_1') {
    $view->set_items_per_page(variable_get('ca_gallery_list_count', 5));
  }
  elseif ($display_id == 'ca_event_block_1') {
    $view->set_items_per_page(variable_get('ca_gallery_block_count', 1));
  }
}

/**
* Implementation of hook_ctools_plugin_directory()
*/
function ca_gallery_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;;
  }
}
